### ISSUE TITLE
Error with a .mp4 build of a playlist [LeeFilm]

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#286] opened 2019-09-03 12:50 UTC
In our playlist section, I have made two playlists. One for sc0460 and one for sc0810.  sc0810 built just fine but sc0460 doesn't build at all. It says there is a build, but it is zero bytes. 
We have renamed sc9460 to sc0460 before.

We have also changed the name of most of the shots in sc0220 from sc9220 and sc09230, so there might be errors there as well.

**Comment by frankrousseau** [comment] 2019-09-09 17:12
The problem is that resolutions are not identical. I close this ticket.

**Closed by frankrousseau** 2019-09-09 17:12 UTC
Labels: bug
