### ISSUE TITLE
Supervisors can't edit playlists

### ISSUE THREAD

**Issue by BenoitGielly** [cgwire/kitsu#1273] opened 2024-01-02 08:38 UTC
**Context**

Studio name:  Stim Studio
Kitsu version: 0.17.54
Production type: Any

**Describe the bug**

According to the documentation, Supervisors should be able to create and edit playlists.
Creation is indeed possible, but afterward, it's impossible to modify or delete them without switching the role to Production Manager.
Did I miss something?

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser Chrome 120.0

**Comment by NicoPennec** [comment] 2024-01-09 18:26
Thanks for your bug report @BenoitGielly 🙏 
The issue is fixed in the latest release of Kitsu (0.17.55)

**Closed by NicoPennec** 2024-01-09 18:26 UTC
Labels: bug

**Comment by BenoitGielly** [comment] 2024-01-10 08:14
Amazing, thank you very much! :)
