### ISSUE TITLE
Vertical scroll bar disapeared in tasktype page

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#475] opened 2020-06-17 09:17 UTC
In a TV Show, Feature films, short Films.

When there are more than 100 assets/shots, and you go to a task type page, the vertical scroll bar disappeared and don't allow you to navigate.

It also happens when the browser window is not fullscreen.

**Comment by frankrousseau** [comment] 2020-06-17 10:15
I cannot reproduce this one. Can you give more information?

**Comment by frankrousseau** [comment] 2020-06-17 12:30
Thanks @gwendupre (video sent via email)

**Comment by frankrousseau** [comment] 2020-07-02 17:06
It should be fixed. Can you try again @gwendupre ?

**Closed** 2020-07-14 14:24 UTC
Labels: bug
