### ISSUE TITLE
Changing type on the existed production make shots list broken

### ISSUE THREAD

**Issue by nekopaldee** [cgwire/kitsu#850] opened 2022-04-13 15:24 UTC
Previously from #849 
I've tried to change from Short to TV Show type to make Sequence Stats appear, but it'll cause a bug that no shot will load up and be stuck at the loading icon. I only have this problem with the existed productions, the new one I've created to test doesn't affect by it.

Kitsu 0.13.57
Zou 0.13.45

![image](https://user-images.githubusercontent.com/26713157/163214494-ee78b743-0b19-4169-b305-fc69431cb299.png)

**Comment by nekopaldee** [comment] 2022-04-14 02:31
Thank you for your response, if it is not supposed to be changed is there any way to disable the option to change it?
I think the ability to change might make some misunderstanding that it is okay to change.

**Comment by frankrousseau** [comment] 2022-04-15 12:57
I thought we blocked it but I will dig into that.

**Comment by frankrousseau** [comment] 2022-04-21 15:29
Duplicate of #482

**Closed as completed by frankrousseau** 2022-04-21 15:29 UTC
Labels: bug
