### ISSUE TITLE
Comments generating events for a task

### ISSUE THREAD

**Issue by xAZR1ELx** [cgwire/kitsu#1268] opened 2023-12-19 10:12 UTC
**Context**

Studio name: JAM Media 
Kitsu version: 0.17.49
Production type:  2D Television

When updating a comment it generates an event for a task. In our case it was setting a tasks status backwards (as screenshots below) 

Images:

![image](https://github.com/cgwire/kitsu/assets/75043222/702408ec-7aed-402a-8716-c42cef51b7ad)

![image](https://github.com/cgwire/kitsu/assets/75043222/d0b5d478-1311-4081-a3e0-d218ebd69bec)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser: Chrome
 - Version: 120.0.6099.109 (Official Build) (64-bit)

**Comment by EvanBldy** [comment] 2024-02-27 01:50
Hi @xAZR1ELx, 
Thanks for your report but I can't reproduce your problem. 
I see that you use Kitsu in 0.17.49 version, this problem is probably fixed since this version (the last version is 0.19.3). 
I close this issue if you see this problem in the last version I let you reopen, thanks

**Closed by EvanBldy** 2024-02-27 01:50 UTC
Labels: bug
