### ISSUE TITLE
My Checks Page, Not all filter / sort dropdowns work

### ISSUE THREAD

**Issue by tetsuoanimation** [cgwire/kitsu#1349] opened 2024-02-21 12:42 UTC
**Context**

Studio name: Tetsuo Animation
Kitsu version: 0.19.2
Production type: Short

**Describe the bug**
Using the 'My Checks Page' as a Studio Manager doesn't let me choose the production in the dropdown and is 'stuck' on 'All Productions'. Sorting the results also doesn't work. - This might be related to the list containing tasks from closed productions.

**Comment by tetsuoanimation** [comment] 2024-02-21 12:52
This is related to the closed projects. Once I removed all closed projects from the page by reopening them and setting the task to 'Done' the dropdowns started working again.

**Comment by NicoPennec** [comment] 2024-02-21 13:36
Hi @tetsuoanimation,
Yes, it's related to the closed project. 
We are preparing a fix.

nb: issue linked to https://github.com/cgwire/kitsu/issues/1348

**Comment by EvanBldy** [comment] 2024-02-21 14:59
Hi @tetsuoanimation, 
Thanks for the report ! 
It's fixed in the last release of Zou (the problem is on Zou side) can you try and close if it's good for you ?

**Closed** 2024-02-27 22:10 UTC
Labels: bug
