### ISSUE TITLE
TagList is obstructed by Asset Fields

### ISSUE THREAD

**Issue by Agamal17** [cgwire/kitsu#1488] opened 2024-07-10 18:02 UTC
**Context**

Studio name: MVS
Kitsu version: 0.19.42
Production type: 

**Describe the bug**

When a metadata filed specifically of type TagList is chosen to be sticked, the list is obstructed by bottom squares.

**Screenshots**

![image](https://github.com/ynput/ayon-kitsu/assets/159413039/ccfe0790-1bb8-4cd8-9bcc-e3db21f5e6e7)

**Desktop (please complete the following information):**

 - OS: Linux
 - Browser: Edge/Chrome/Brave
 - Version: 0.19.42

**Comment by NicoPennec** [comment] 2024-07-11 08:33
hi @Agamal17 
I am unable to replicate the issue right now.
Can you give us more details?
- type of production (see Production > Settings > Type)
- section (assets, shots, ...)
One last request, can you provide a larger screen? Because we cannot see the origin of the square which hides your tag list.

**Comment by Agamal17** [comment] 2024-07-11 12:43
Type of Production: Feature Film
Section: Shots

![image](https://github.com/cgwire/kitsu/assets/159413039/c0b22899-0c73-491d-b8b9-71c62c595021)

**Comment by NicoPennec** [comment] 2024-07-16 07:57
Thanks @Agamal17 for the additional information.
The issue is fixed on Kitsu >= v0.19.48

**Closed by NicoPennec** 2024-07-16 07:57 UTC
Labels: bug
